id = "reality"
name = "Reality Language Support"
version = "0.0.1"
schema_version = 1
authors = ["Thomas Vergne <contact@thomas-vergne.fr>"]
description = "Syntax highlighting and LSP support for Reality language"
repository = "https://github.com/thomasvergne/reality-lang"

[grammars.reality]
repository = "https://github.com/thomasvergne/reality-lang"
rev = "main"
path = "packages/tree-sitter"

[language_servers.reality]
name = "Reality Language Server"
languages = ["Reality"]
