name = "Reality"
grammar = "reality"
path_suffixes = ["rl"]
line_comments = ["// "]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string_literal",
        "comment",
    ] },
]
